name: warc
description: WARC (web archive file format) reader (parser).
version: 0.0.2
homepage: https://github.com/agilord/warc

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:

dev_dependencies:
  base32: ^2.0.0
  buffer: ^1.1.0
  crypto: ^3.0.1
  lints: ^1.0.0
  test: ^1.16.0
