name: warc
description: WARC (web archive file format) reader (parser) and recorder.
version: 0.0.6
homepage: https://github.com/agilord/warc

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  buffer: ^1.1.0
  convert: ^3.0.1
  crypto: ^3.0.1
  path: ^1.8.0
  synchronized: ^3.0.0

dev_dependencies:
  base32: ^2.0.0
  lints: ^1.0.0
  test: ^1.16.0
